services:
  postgres:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: testdb
    tty: true
    # restart: always
    volumes:
      - ./docker/postgresql/initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
  webapp:
    depends_on:
      - postgres
    # image: "ghcr.io/pollenjp/sandbox-http-server-go:latest"
    image: "pollenjp/sandbox-http-server-go:latest"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      # SERVER_ADDRESS: 127.0.0.1
      SERVER_PORT: 8080
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: testuser
      DB_NAME: testdb
      DB_PASSWORD: password
      DB_OPTIONS: sslmode=disable
    expose:
      - 8080
  nginx:
    image: nginx:latest
    depends_on:
      - webapp
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_data:/var/log/nginx
    ports:
      - "80:80"
volumes:
  postgres_data:
    driver: local
  nginx_data:
    driver: local
