name: go code check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*

jobs:
  go_mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: go mod
        run: |
          go mod tidy

          # check dirty
          if ! git diff --quiet; then git status; exit 1; fi
