name: go test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - release/*
    paths:
      - "**.go"
      - .golangci.yml

jobs:
  go_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.19.0"

      - name: go test
        run: |
          go test -v ./...
